[package]
name = "tycho-collator"
description = "A collator node."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
anyhow = { workspace = true }
async-trait = { workspace = true }
bytesize = { workspace = true }
futures-util = { workspace = true }
rand = { workspace = true }
tl-proto = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

everscale-types = { workspace = true }
everscale-crypto = { workspace = true }

# local deps
tycho-core = { workspace = true }
#tycho-consensus = { workspace = true }
tycho-network = { workspace = true }
tycho-storage = { workspace = true }
tycho-util = { workspace = true }
tycho-block-util = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tracing-test = { workspace = true }
tycho-core = { workspace = true, features = ["test"] }
tycho-storage = { workspace = true, features = ["test"] }

[features]
test = []

[lints]
workspace = true
