[package]
name = "tycho-collator"
description = "A collator node."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps

# local deps
tycho-core = { workspace = true }
tycho-consensus = { workspace = true }
tycho-storage = { workspace = true }
tycho-util = { workspace = true }

[lints]
workspace = true
