apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  labels:
    {{- include "tycho.labels" . | nindent 4 }}
data:
  global-config.json: |
    {{- .Values.config.globalConfig | nindent 4 }}
