apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tycho.fullname" . }}-keys
  labels:
    {{- include "tycho.labels" . | nindent 4 }}
data:
{{- range $i, $e := .Values.keys }}
    {{ $i }}: {{ . | b64enc }}
{{- end }}
