apiVersion: v1
kind: Service
metadata:
  name: {{ include "tycho.fullname" . }}
  labels:
    {{- include "tycho.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: UDP
      name: udp
   {{- if .Values.serviceMonitor.enabled }}
    - port: {{ .Values.serviceMonitor.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
   {{- end }}


  selector:
    {{- include "tycho.selectorLabels" . | nindent 4 }}
