apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tycho.fullname" . }}
  labels:
    {{- include "tycho.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      {{- include "tycho.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "tycho.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tycho.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tycho.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - bash
            - -c
            - >
              export INDEX=$((${HOSTNAME##*-}));
              export KEY="$(</keys/$INDEX)";
              /app/network-node run 0.0.0.0:30310 $TYCHO_POD_IP:30310 --key $KEY --global-config /app/global-config.json
          env:
            - name: RUST_LOG
              value: {{ .Values.config.rustLog | quote }}
            - name: TYCHO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: udp
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          {{- if .Values.serviceMonitor.enabled }}
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
