[package]
name = "tycho-cli"
description = "Node CLI."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "tycho"
path = "./src/main.rs"

[dependencies]
# crates.io deps
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tikv-jemallocator = { version = "0.5", features = [
    "unprefixed_malloc_on_supported_platforms",
    "background_threads",
], optional = true }

# local deps

[build-dependencies]
anyhow = "1"
rustc_version = "0.4"

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]

[lints]
workspace = true
