[package]
name = "tycho-network"
version = "0.0.1"
edition = "2021"
description = "A peer-to-peer networking library."
include = ["src/**/*.rs", "src/**/*.tl"]

[dependencies]
# crates.io deps
anyhow = "1.0"
ed25519 = { version = "2.0", features = ["alloc", "pkcs8"] }
hex = "0.4"
pin-project-lite = "0.2"
pkcs8 = "0.10"
quinn = { version = "0.10", features = ["runtime-tokio", "tls-rustls"] }
rcgen = "0.11"
ring = "0.16"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-webpki = "0.101"
serde = "1.0"
thiserror = "1"
tl-proto = "0.4"
tokio = { version = "1", features = ["rt", "sync"] }
tracing = "0.1"
x509-parser = "0.15"

# local deps
tycho-util = { path = "../util", version = "=0.0.1" }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }

[lints]
workspace = true
