[package]
name = "tycho-network"
version = "0.0.1"
edition = "2021"
description = "A peer-to-peer networking library."

[dependencies]
# creates.io deps

# local deps
tycho-util = { path = "../util", version = "=0.0.1" }

[lints]
workspace= true