[package]
name = "tycho-core"
version = "0.0.1"
edition = "2021"
description = "Basic functionality of peer."

[dependencies]
# creates.io deps

# local deps
tycho-network = { path = "../network", version = "=0.0.1" }
tycho-storage = { path = "../storage", version = "=0.0.1" }
tycho-util = { path = "../util", version = "=0.0.1" }
