[package]
name = "tycho-core"
description = "Basic functionality of peer."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
anyhow = { workspace = true }
everscale-types = { workspace = true }
tokio = { workspace = true }

# local deps
tycho-network = { workspace = true }
tycho-storage = { workspace = true }
tycho-util = { workspace = true }

[lints]
workspace = true
