[package]
name = "tycho-util"
version = "0.0.1"
edition = "2021"
description = "Shared utilities for node components."

[dependencies]
# crates.io deps
ahash = "0.8"
dashmap = "5.4"
rand = "0.8"
tokio = { version = "1", default-features = false, features = ["time"] }

# local deps

[lints]
workspace = true
