[package]
name = "tycho-util"
description = "Shared utilities for node components."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
ahash = "0.8"
castaway = "0.2"
dashmap = "5.4"
futures-util = "0.3"
hex = "0.4"
humantime = "2"
libc = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", default-features = false, features = ["time", "sync", "rt"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", default-features = false, features = [
    "time",
    "sync",
    "rt-multi-thread",
    "macros",
] }

[lints]
workspace = true
