[package]
name = "tycho-util"
version = "0.0.1"
edition = "2021"
description = "Shared utilities for node components."

[dependencies]
# crates.io deps
ahash = "0.8"
castaway = "0.2"
dashmap = "5.4"
futures-util = "0.3"
hex = "0.4"
humantime = "2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", default-features = false, features = ["time", "sync"] }

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["time", "sync", "rt-multi-thread", "macros"] }

[lints]
workspace = true
