[package]
name = "tycho-storage"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
anyhow = "1.0.79"
arc-swap = "1.6.0"
bumpalo = "3.14.0"
bytes = "1.5.0"
bytesize = { version = "1.3.0", features = ["serde"] }
crc = "3.0.1"
dashmap = "5.5.3"
everscale-types = "0.1.0-rc.6"
fdlimit = "0.3.0"
hex = "0.4.3"
humantime = "2.1.0"
libc = "0.2.153"
num-traits = "0.2.18"
parking_lot = "0.12.1"
parking_lot_core = "0.9.9"
quick_cache = "0.4.1"
rlimit = "0.10.1"
serde = { version = "1.0.196", features = ["derive"] }
sha2 = "0.10.8"
smallvec = "1.13.1"
sysinfo = "0.30.5"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1"
triomphe = "0.1.11"
weedb = "0.1.1"

# local deps
tycho-block-util = { path = "../block-util" }
tycho-util = { path = "../util" }

[dev-dependencies]
base64 = "0.22.0"
serde_json = "1.0.114"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2"
tempfile = "3.10"

[lints]
workspace = true
