[package]
name = "tycho-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
everscale-types = "0.1.0-rc.6"
anyhow = "1.0.79"
bytes = "1.5.0"

tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1"
thiserror = "1.0.57"
hex = "0.4.3"
libc = "0.2.153"
smallvec = "1.13.1"
sha2 = "0.10.8"

tycho-block-util = { path = "../block-util" }
tycho-util = { path = "../util" }

dashmap = "5.5.3"
bumpalo = "3.14.0"
arc-swap = "1.6.0"
crc = "3.0.1"
bytesize = { version = "1.3.0", features = ["serde"] }
parking_lot = "0.12.1"
quick_cache = "0.4.1"
parking_lot_core = "0.9.9"
serde = { version = "1.0.196", features = ["derive"] }

weedb = "0.1.1"
rlimit = "0.10.1"
fdlimit = "0.3.0"
humantime = "2.1.0"
sysinfo = "0.30.5"
triomphe = "0.1.11"
num-traits = "0.2.18"

[lints]
workspace = true
