[package]
name = "tycho-block-util"
description = "Shared utilities for blockchain models."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
anyhow = "1.0.81"
bytes = "1.5.0"
everscale-types = "0.1.0-rc.6"
hex = "0.4.3"
parking_lot = "0.12.1"
sha2 = "0.10.8"
smallvec = "1.13"
thiserror = "1.0.58"

# local deps
tycho-util = { path = "../util" }

[dev-dependencies]
rand = "0.8"

[lints]
workspace = true
