[package]
name = "tycho-consensus"
version = "0.0.1"
edition = "2021"
description = "DAG-based consensus for external messages queue."

[dependencies]
# crates.io deps

# local deps
tycho-network = { path = "../network", version = "=0.0.1" }
tycho-storage = { path = "../storage", version = "=0.0.1" }
tycho-util = { path = "../util", version = "=0.0.1" }
