[package]
name = "tycho-consensus"
description = "DAG-based consensus for external messages queue."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
anyhow = "1.0"
bincode = "1.3"
bytes = { version = "1.0", features = ["serde"] }
futures-util = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
weedb = "0.1"

# local deps
tycho-network = { path = "../network", version = "=0.0.1" }
tycho-storage = { path = "../storage", version = "=0.0.1" }
tycho-util = { path = "../util", version = "=0.0.1" }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-test = "0.2"

[lints]
workspace = true
