[package]
name = "tycho-consensus"
description = "DAG-based consensus for external messages queue."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# crates.io deps
anyhow = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
castaway = "0.2"
dashmap = "5.4"
everscale-crypto = "0.2"
futures-util = { workspace = true }
parking_lot = "0.12"
rand = { version = "0.8" }
rand_pcg = { version = "0.3" }
serde = { workspace = true, features = ["derive"] }
sha2 = "0.10"
tokio = { version = "1", features = ["rt"] }
tracing = { workspace = true }
weedb = { workspace = true }

# local deps
tycho-network = { workspace = true }
tycho-storage = { workspace = true }
tycho-util = { workspace = true }

# temp
#hex = "0.4.3"
thiserror = "1.0"
ahash = "0.8"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
