[package]
name = "tycho-consensus"
version = "0.0.1"
edition = "2021"
description = "DAG-based consensus for external messages queue."

[dependencies]
# crates.io deps
anyhow = "1.0"
bincode = "1.3"
bytes = { version = "1.0", features = ["serde"] }
castaway = "0.2"
dashmap = "5.4"
everscale-crypto = "0.2"
futures-util = { version = "0.3" }
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "1", features = ["rt"] }
tracing = "0.1"
weedb = "0.1"

# local deps
tycho-network = { path = "../network" }
tycho-storage = { path = "../storage" }
tycho-util = { path = "../util" }

# temp
#hex = "0.4.3"
thiserror = "1.0"
ahash = "0.8"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-test = "0.2"

[lints]
workspace = true
